services:
  db:
    image: postgres:15
    container_name: bank-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: bank_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: bank-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  redis:
    image: redis:7-alpine
    container_name: bank-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: bank-app
    depends_on:
      - db
      - redis
      - prometheus
      - grafana
    environment:
      APP_PORT: "8080"
      JWT_SECRET: "devsecret"
      TOKEN_TTL: "1h"
      SEED_ADMIN: "true"
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: bank_db
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_PASSWORD: ""
      REDIS_DB: "0"
    ports:
      - "8080:8080"
    command: ["./bank-api"]

  prometheus:
    image: prom/prometheus:latest
    container_name: bank-prometheus
    restart: always
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: bank-grafana
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  pgdata:
  redis_data:
  prometheus_data:
